import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CookieConsent from "@/app/components/CookiePolicy";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bognart Design",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="hu" className="scroll-smooth">

      <head>
      <script defer src="https://cloud.umami.is/script.js" data-website-id="39555d77-4acc-4018-bc4b-426d0b7d75a9"></script>

      </head>
      <body className="relative min-h-dvh antialiased">
      {/* Global fixed background (clipped) */}
      <div
          aria-hidden
          className="fixed inset-0 -z-10 overflow-hidden pointer-events-none"
      >
          {/* Clip the image container to any shape you like */}
          <div >
              <img
                  src="/hero.webp"
                  alt=""
                  className="h-full w-full object-top object-cover"
                  loading="eager"
              />
              {/* Soft overlay for readability (optional) */}
              <div className="absolute inset-0 bg-stone-50/20" />
          </div>
      </div>

      {/* Your whole app scrolls over the fixed bg */}
      {children}
      <CookieConsent />
      </body>

      </html>
  );
}
