// lib/projects.js

export const projects = [
    {
        slug: "project-1",
        title: "Modern természetesség",
        cover: "/pr1.jpg", // card image
        blurb: "Világos tónusok, természetes anyagok és letisztult formák találkozása.",
        images: [
            "/projects/project-1/1.jpg",
            "/projects/project-1/2.jpg",
            "/projects/project-1/3.jpg",
            "/projects/project-1/4.jpg",
            "/projects/project-1/5.jpg",
            "/projects/project-1/6.jpg",
            "/projects/project-1/7.jpg",
            "/projects/project-1/8.jpg",
            "/projects/project-1/9.jpg",
            "/projects/project-1/10.jpg",
            "/projects/project-1/11.jpg",
            "/projects/project-1/12.jpg",
            "/projects/project-1/13.jpg",
            "/projects/project-1/14.jpg",
            "/projects/project-1/15.jpg",
            "/projects/project-1/16.jpg",
            "/projects/project-1/17.jpg",
            "/projects/project-1/18.jpg",
            "/projects/project-1/19.jpg",
            "/projects/project-1/20.jpg",
            "/projects/project-1/21.jpg",
            "/projects/project-1/22.jpg",
            "/projects/project-1/23.jpg",
            "/projects/project-1/24.jpg",
            "/projects/project-1/25.jpg",
            "/projects/project-1/26.jpg",
            "/projects/project-1/27.jpg",
            "/projects/project-1/28.jpg",
            "/projects/project-1/028.jpg",
            "/projects/project-1/29.jpg",
            "/projects/project-1/30.jpg",
            "/projects/project-1/31.jpg",
            "/projects/project-1/32.jpg",
            "/projects/project-1/33.jpg",
            "/projects/project-1/34.jpg",
            "/projects/project-1/35.jpg",
            "/projects/project-1/36.jpg",
            "/projects/project-1/37.jpg",
            "/projects/project-1/38.jpg",
            "/projects/project-1/39.jpg",
            "/projects/project-1/40.jpg",
            "/projects/project-1/41.jpg",
            "/projects/project-1/42.jpg",
            "/projects/project-1/43.jpg",
            "/projects/project-1/44.jpg",
            "/projects/project-1/45.jpg",
            "/projects/project-1/46.jpg",
            "/projects/project-1/47.jpg",
            "/projects/project-1/48.jpg",
            "/projects/project-1/49.jpg",
            "/projects/project-1/50.jpg",
            "/projects/project-1/51.jpg",

        ],
    },
    {
        slug: "project-2",
        title: "Klasszikus Harmónia – Időtlen Otthon",
        cover: "/pr2.webp",
        blurb: "A letisztult vonalak, a természetes anyagok és a meleg tónusok időtlen hangulatot árasztanak, miközben minden részlet a nyugodt, harmonikus élettér megteremtését szolgálja.",
        images: [
            "/projects/project-2/1.jpg",
            "/projects/project-2/2.jpg",
            "/projects/project-2/3.jpg",
            "/projects/project-2/4.jpg",
            "/projects/project-2/5.jpg",
            "/projects/project-2/6.jpg",
            "/projects/project-2/7.jpg",
            "/projects/project-2/8.jpg",
            "/projects/project-2/9.webp",
            "/projects/project-2/10.png",
            "/projects/project-2/11.png",
            "/projects/project-2/12.jpg",
            "/projects/project-2/13.jpg",
            "/projects/project-2/14.jpg",
            "/projects/project-2/15.jpg",
            "/projects/project-2/16.jpg",
            "/projects/project-2/17.jpg",
            "/projects/project-2/18.png",
            "/projects/project-2/19.png",
            "/projects/project-2/20.jpg",
            "/projects/project-2/21.jpg",
        ],
    },
    {
        slug: "project-3",
        title: "Modern Letisztultság – Természetes Elegancia",
        cover: "/pr3.jpg",
        blurb: "A világos tónusok, a fa részletek és a puha textúrák meleg, hívogató légkört teremtenek, miközben a praktikus térszervezés a modern élet minden igényét kiszolgálja.",
        images: [
            "/projects/project-3/1.jpg",
            "/projects/project-3/2.jpg",
            "/projects/project-3/3.jpg",
            "/projects/project-3/4.jpg",
            "/projects/project-3/5.jpg",
            "/projects/project-3/6.jpg",
            "/projects/project-3/7.jpg",
            "/projects/project-3/8.jpg",
            "/projects/project-3/9.jpg",
            "/projects/project-3/10.jpg",
            "/projects/project-3/11.jpg",
            "/projects/project-3/12.jpg",
            "/projects/project-3/13.jpg",
            "/projects/project-3/14.jpg",
            "/projects/project-3/15.jpg",
            "/projects/project-3/17.jpg",
            "/projects/project-3/18.jpg",
            "/projects/project-3/19.jpg",
            "/projects/project-3/20.jpg",
            "/projects/project-3/21.jpg",
            "/projects/project-3/22.jpg",
            "/projects/project-3/23.jpg",
            "/projects/project-3/24.jpg",
        ],
    },
    {
        slug: "project-4",
        title: "Letisztult Élettér - Airbnb lakás",
        cover: "/pr4.jpg",
        blurb: "A fürdő és a konyha finoman összehangolt színvilága, a nappali és étkező meleg tónusai otthonos, mégis friss atmoszférát teremtenek, amely időtálló marad.",
        images: [

            "/projects/project-4/02.jpg",
            "/projects/project-4/03.jpg",
            "/projects/project-4/04.jpg",
            "/projects/project-4/05.jpg",
            "/projects/project-4/06.jpg",
            "/projects/project-4/07.jpg",
            "/projects/project-4/08.jpg",
            "/projects/project-4/09.jpg",
            "/projects/project-4/10.jpg",
            "/projects/project-4/11.jpg",
            "/projects/project-4/12.jpg",
            "/projects/project-4/13.jpg",
            "/projects/project-4/14.jpg",

        ],
    },
    {
        slug: "project-5",
        title: "Időtlen elegancia",
        cover: "/pr5.png",
        blurb: "Letisztult arányok, nemes anyagok és finom részletek, melyek sosem mennek ki a divatból.",
        images: [
            "/projects/project-5/1.png",
            "/projects/project-5/2.png",
            "/projects/project-5/3.png",
            "/projects/project-5/4.png",
            "/projects/project-5/5.png",
            "/projects/project-5/6.png",
            "/projects/project-5/7.png",
            "/projects/project-5/8.png",
            "/projects/project-5/9.png",
            "/projects/project-5/10.png",
            "/projects/project-5/11.png",
            "/projects/project-5/12.png",
            "/projects/project-5/13.png",
            "/projects/project-5/14.png",
            "/projects/project-5/15.png",
            "/projects/project-5/16.png",
            "/projects/project-5/17.png",
            "/projects/project-5/18.png",
        ],
    },
    {
        slug: "project-6",
        title: "Japandi Konyha",
        cover: "/pr6.jpg",
        blurb: "A tágas elrendezés és az egyszerű, mégis kifinomult részletek nemcsak esztétikai élményt nyújtanak, hanem a mindennapi használatban is maximális kényelmet biztosítanak.",
        images: [
            "/projects/project-6/1.jpg",
            "/projects/project-6/2.jpg",
            "/projects/project-6/3.jpg",
            "/projects/project-6/4.jpg",
            "/projects/project-6/5.png",
        ],
    },
    {
        slug: "project-7",
        title: "Project 7",
        cover: "/pr7.png",
        blurb: "Praesent euismod dignissim velit a elementum.",
        images: [
            "/projects/project-7/1.jpg",
            "/projects/project-7/2.jpg",
            "/projects/project-7/3.jpg",
        ],
    },

];


export function getProject(slug) {
    const raw = Array.isArray(slug) ? slug[0] : slug;

    const key = decodeURIComponent(String(raw ?? ""))
        .trim()
        .toLowerCase();

    return projects.find((p) => String(p.slug).toLowerCase() === key) || null;
}

export function getProjectParams() {
    return projects.map((p) => ({ slug: p.slug }));
}